### PR TITLE
YouTube NonStop implementation and Tray System

### PR DESCRIPTION
**Pull request by IamM47Z**
I've implemented this extension (https://chrome.google.com/webstore/detail/youtube-nonstop/nlkaejimjacpillmajjnopmpbkbnocid) to the code and a tray system so we can minimize the app to the tray.
I also figured out that the pause system dont work if youtube is not in english but i havent fixed it yet.
If you can take a look to my changes and see if they are 100% compatible with this new changes i would appreciate.

### CODE REVIEW

**Comment by IamM47Z** [comment]
also i think that increasing this interval `setInterval(updateSongInfo, 250);` to a higher value or make it costumizable would be an incredible adjust since it actually impacts in the system performance.

**Comment by BigBrainAFK** [comment]
> 
> 
> also i think that increasing this interval `setInterval(updateSongInfo, 250);` to a higher value or make it costumizable would be an incredible adjust since it actually impacts in the system performance.

I wish Id be able to make a bit more progress on the settings hooking so I could give a few more customization options.
For now I think I'll increase it to a second or so

**Review by Matix-Media — APPROVED** [review]
How can I remove a comment?

**Comment by BigBrainAFK** [comment]
Did you test it Matix?

**Comment by Matix-Media** [comment]
Nope

**Comment by Matix-Media** [comment]
Thats why I wanted to deleted the xomment

**Comment by BigBrainAFK** [comment]
So I did try it and it does not work.

[Image](https://discordjs.moe/p7w9528kj8k3.png)

**Comment by IamM47Z** [comment]
might have been due to an update but when i forked it was working, i will take a look and see

**Comment by IamM47Z** [comment]
meanwhile im not on my laptop i think this repo might be interesting to the project itself: https://github.com/Volcomix/youtube-music-nonstop

**Pull request closed without merging**
